# Test script for Send-DeletionSummaryEmail function
# This script tests the email creation without actually deleting any messages

# Function to send deletion summary email to Outlook Inbox
function Send-DeletionSummaryEmail {
    param(
        $outlook,
        $deletedCount,
        $failedCount,
        $deletedItems,      # Array of deleted messages
        $failedItems,       # Array of failed messages (if any)
        $backupLocation,
        $operationMode      # "PST" or "MSG"
    )

    try {
        Write-Host "`n[EMAIL] Creating deletion summary email..." -ForegroundColor Cyan

        # Get the default Outlook folder (Inbox)
        $namespace = $outlook.GetNamespace("MAPI")
        $inboxFolder = $namespace.GetDefaultFolder(6)  # 6 = Inbox

        # Create new mail item
        $mailItem = $outlook.CreateItem(0)  # 0 = olMailItem

        # Set email properties
        $operationDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        $mailItem.Subject = "Large Messages Cleanup Report - $(Get-Date -Format 'yyyy-MM-dd')"
        $mailItem.BodyFormat = 2  # 2 = olFormatHTML

        # Build HTML body
        $htmlBody = @"
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; color: #333; }
        h2 { color: #0078d4; border-bottom: 2px solid #0078d4; padding-bottom: 10px; }
        .summary { background-color: #f0f0f0; padding: 15px; margin: 15px 0; border-left: 4px solid #0078d4; }
        .summary-item { margin: 8px 0; }
        .summary-item strong { color: #0078d4; }
        table { border-collapse: collapse; width: 100%; margin: 15px 0; }
        th { background-color: #0078d4; color: white; padding: 10px; text-align: left; border: 1px solid #999; }
        td { padding: 10px; border: 1px solid #ddd; }
        tr:nth-child(even) { background-color: #f9f9f9; }
        .success { color: #107c10; }
        .failed { color: #d83b01; }
        .timestamp { color: #666; font-size: 12px; }
        .note { color: #666; font-size: 12px; margin-top: 15px; padding-top: 15px; border-top: 1px solid #ddd; }
    </style>
</head>
<body>
    <h2>Large Messages Cleanup Report</h2>

    <div class="summary">
        <div class="summary-item"><strong>Operation Date:</strong> $operationDate</div>
        <div class="summary-item"><strong>Mode:</strong> $operationMode Export and Delete</div>
        <div class="summary-item"><strong>Backup Location:</strong> $backupLocation</div>
        <div class="summary-item"><strong>Status:</strong> <span class="success">Completed</span></div>
    </div>

    <h2>Summary Statistics</h2>
    <div class="summary">
        <div class="summary-item"><strong>Successfully Deleted:</strong> <span class="success">$deletedCount message(s)</span></div>
        <div class="summary-item"><strong>Failed:</strong> <span class="failed">$failedCount message(s)</span></div>
"@

        # Add deleted items table if any
        if ($deletedItems -and $deletedItems.Count -gt 0) {
            $htmlBody += @"
    </div>

    <h2>Deleted Messages</h2>
    <table>
        <tr>
            <th>No</th>
            <th>Subject</th>
            <th>From</th>
            <th>Size (MB)</th>
            <th>Original Folder</th>
        </tr>
"@
            $counter = 1
            foreach ($item in $deletedItems) {
                $htmlBody += @"
        <tr>
            <td>$counter</td>
            <td>$($item.Subject)</td>
            <td>$($item.From)</td>
            <td>$($item.SizeMB)</td>
            <td>$($item.FolderPath)</td>
        </tr>
"@
                $counter++
            }
            $htmlBody += "</table>"
        }

        # Add failed items table if any
        if ($failedItems -and $failedItems.Count -gt 0) {
            $htmlBody += @"
    <h2>Failed Messages</h2>
    <table>
        <tr>
            <th>Subject</th>
            <th>From</th>
            <th>Size (MB)</th>
            <th>Error</th>
        </tr>
"@
            foreach ($item in $failedItems) {
                $htmlBody += @"
        <tr>
            <td>$($item.Subject)</td>
            <td>$($item.From)</td>
            <td>$($item.SizeMB)</td>
            <td class="failed">$($item.Error)</td>
        </tr>
"@
            }
            $htmlBody += "</table>"
        }

        $htmlBody += @"
    <div class="note">
        <p><strong>Note:</strong> This email was automatically generated by the Dualog Webmail Super Script.</p>
        <p>Backup files are stored at: <strong>$backupLocation</strong></p>
"@

        if ($operationMode -eq "PST") {
            $htmlBody += @"
        <p>Your deleted messages are archived in a PST file that is currently attached to your Outlook.</p>
"@
        } else {
            $htmlBody += @"
        <p>Your deleted messages are saved as individual MSG files in the backup directory.</p>
"@
        }

        $htmlBody += @"
    </div>
</body>
</html>
"@

        # Set the HTML body
        $mailItem.HTMLBody = $htmlBody

        # Save to Inbox (without sending)
        $mailItem.Move($inboxFolder)

        Write-Host "[EMAIL CREATED] Summary email saved to Inbox" -ForegroundColor Green

        return $true
    }
    catch {
        Write-Host "[WARNING] Failed to create summary email: $($_.Exception.Message)" -ForegroundColor Yellow
        return $false
    }
}

# ============================================================================
# TEST EXECUTION
# ============================================================================

Write-Host ""
Write-Host "Test: Send-DeletionSummaryEmail Function" -ForegroundColor Cyan
Write-Host ""

try {
    # Check if Outlook is running
    Write-Host "[CHECK] Checking for Outlook..." -ForegroundColor Yellow
    $outlook = New-Object -ComObject Outlook.Application
    Write-Host "[OK] Outlook is available" -ForegroundColor Green
    Write-Host ""

    # Create sample deleted items data
    Write-Host "[SAMPLE] Creating sample data..." -ForegroundColor Yellow
    $deletedItems = @(
        [PSCustomObject]@{
            Subject = "Large Project File with Attachments"
            From = "john.smith@example.com"
            SizeMB = 87.5
            FolderPath = "Inbox\Work\Projects"
        },
        [PSCustomObject]@{
            Subject = "Video Recording Q1 Meeting"
            From = "meeting.organizer@company.com"
            SizeMB = 156.2
            FolderPath = "Inbox\Meetings"
        },
        [PSCustomObject]@{
            Subject = "Design Files and Assets"
            From = "design.team@company.com"
            SizeMB = 203.8
            FolderPath = "Inbox\Design\Archive"
        },
        [PSCustomObject]@{
            Subject = "Backup Database Export"
            From = "admin@company.com"
            SizeMB = 512.4
            FolderPath = "Inbox\IT\Backups"
        }
    )

    # Create sample failed items data
    $failedItems = @(
        [PSCustomObject]@{
            Subject = "Corrupted Email Cannot Delete"
            From = "unknown@example.com"
            SizeMB = 45.1
            Error = "Item is locked by another process"
        }
    )

    Write-Host "[OK] Sample data created" -ForegroundColor Green
    Write-Host ""

    # Call the function
    Write-Host "[SENDING] Creating test email..." -ForegroundColor Yellow
    $backupPath = "C:\Dualog\deleteditems"

    $result = Send-DeletionSummaryEmail -outlook $outlook `
        -deletedCount $deletedItems.Count `
        -failedCount $failedItems.Count `
        -deletedItems $deletedItems `
        -failedItems $failedItems `
        -backupLocation $backupPath `
        -operationMode "PST"

    Write-Host ""
    Write-Host "Test Results" -ForegroundColor Cyan
    Write-Host ""

    if ($result) {
        Write-Host "SUCCESS: Email successfully created" -ForegroundColor Green
        Write-Host ""
        Write-Host "Details:" -ForegroundColor Cyan
        Write-Host "  Subject: Large Messages Cleanup Report" -ForegroundColor White
        Write-Host "  Location: Outlook Inbox" -ForegroundColor White
        Write-Host "  Mode: PST Export and Delete" -ForegroundColor White
        Write-Host "  Deleted: $($deletedItems.Count) messages" -ForegroundColor White
        Write-Host "  Failed: $($failedItems.Count) messages" -ForegroundColor White
        Write-Host "  Backup: $backupPath" -ForegroundColor White
        Write-Host ""
        Write-Host "Next Step: Open Outlook and check your Inbox for the new email" -ForegroundColor Yellow
    }
    else {
        Write-Host "FAILED: Could not create email" -ForegroundColor Red
    }

}
catch {
    Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host ""
    Write-Host "Make sure Outlook is installed and running" -ForegroundColor Yellow
}

Write-Host ""
